### ISSUE TITLE
Header position/text alignment - Send Gold Mobile Sim

### ISSUE THREAD

**Issue by HugTeddy** [ImY0mu/SimpleMMO-Hub-Dist#1]
Hub Version: 0.0.6-21.12.2

The header on the send gold page shows a generic "player" name rather than the username of the player you are sending gold to. This might be easier to see if the name was next to the avatar and the player was listed on the right instead. Similar to guilds where the guild name should be next to the avatar and type placed on the other side.

 
![image](https://user-images.githubusercontent.com/62405530/144271289-827c1820-7cc6-4e43-bea9-b30b6f7380e3.png)

**Comment by ImY0mu** [comment]
Sadly issue on Mike's side, so closing it now.
