### ISSUE TITLE
Statistics Layout

### ISSUE THREAD

**Issue by HugTeddy** [ImY0mu/SimpleMMO-Hub-Dist#10]
Consider formatting the statistics section a little differently? I believe the top four are more likely to be used/needed rather than the crafting skills data. 

![image](https://user-images.githubusercontent.com/62405530/145632833-e3b7e628-b85d-4067-a862-c47b0e6e233a.png)

**Comment by ImY0mu** [comment]
I have attempted to do something similar due to some size limitations.
