### ISSUE TITLE
Stuck On Account Select

### ISSUE THREAD

**Issue by Tartarus6** [ImY0mu/SimpleMMO-Hub-Dist#11]
I'd had it downloaded for a while but it froze when I updated it. so I uninstalled and redownloaded, but now I can't get off of this screen. I can't do anything except for resizing, minimizing, and closing the window.

![Screenshot 2022-03-07 161606](https://user-images.githubusercontent.com/88263600/157119295-dbf99650-4659-4aa2-a2fd-43ef911c8a5f.png)

**Comment by Tartarus6** [comment]
Upon further inspection this also happens for some reason.

https://user-images.githubusercontent.com/88263600/157120915-1d9fc043-07f1-4cc8-bbea-b2fa11e2b666.mp4

**Comment by ImY0mu** [comment]
Greetings,

thank you for letting me know about the issue you have experienced. It is not something I can fix at this moment, but could you please try uninstalling the client, deleting the folder at "%appdata%/roaming/SimpleMMO Hub V2" and then install it again? To see if a fresh start will make it work for you.

I predicted some bugs will occur even after spending few hours debugging. I have some basic idea what might be the issue, so thank you for bringing this up.

Please let me know if the fresh start helped.

**Comment by Tartarus6** [comment]
yes, resetting that file fixed it.

**Comment by ImY0mu** [comment]
I am glad it helped, I will look into the issue tomorrow to see if there is something I can do about it.

Have fun playing! 👀

**Comment by ImY0mu** [comment]
Should be fixed at the new version. My apologies for the inconvenience.
