### ISSUE TITLE
Incorrect Stats

### ISSUE THREAD

**Issue by Tartarus6** [ImY0mu/SimpleMMO-Hub-Dist#12]
On the main page, the skill levels that are shown are wrong.

In the app:
![Screenshot 2022-03-09 160803](https://user-images.githubusercontent.com/88263600/157536362-11253f09-5006-4c37-b304-cff6c8ec8670.png)

On the website:
![Screenshot 2022-03-09 160642](https://user-images.githubusercontent.com/88263600/157536164-207060a4-a6f1-46fd-a601-f61660901b21.png)

**Comment by ImY0mu** [comment]
That is really weird, as it shows them correctly for me when I compare them with web app and android apk profiles. 🤔

**Comment by Tartarus6** [comment]
When you were having me run the commands in the terminal, the stats that showed there were incorrect as well.

**Comment by ImY0mu** [comment]
Then it may have to be an error on Mike's side, as the code is same for every user of my client and mine stats are correct. 👀

**Comment by Tartarus6** [comment]
the bug isn't there on the public api, hmm.

[{'skill': 'crafting', 'level': 7, 'exp': 1237}, {'skill': 'treasurehunter', 'level': 62, 'exp': 97404}, {'skill': 'fishing', 'level': 58, 'exp': 83857}, {'skill': 'mining', 'level': 57, 'exp': 82024}, {'skill': 'woodcutting', 'level': 56, 'exp': 77974}, {'skill': 'event', 'level': 33, 'exp': 27503}]

**Comment by ImY0mu** [comment]
You are right. I found where was the issue. Apologies for my denial, I could not find it at first. 

I will release the fix with the next update, thank you again!
