### ISSUE TITLE
Guild Bank Missing Buttons

### ISSUE THREAD

**Issue by Tartarus6** [ImY0mu/SimpleMMO-Hub-Dist#13]
As of the new update, guilds can have co-leaders and officers. Co-leaders should be able to withdraw from the guild's bank.

SS from mobile sim: 
![Screenshot 2022-04-18 162830](https://user-images.githubusercontent.com/88263600/163872840-1871c41a-42e4-4777-b99a-9426685dbc99.png) 

SS from website:
![Screenshot 2022-04-18 163003](https://user-images.githubusercontent.com/88263600/163873024-a0802d5b-66fe-48c5-a6f6-0ec5b16f157b.png)

**Comment by ImY0mu** [comment]
Greetings,
Thank you for the report, but that is an issue of mobile version of SimpleMMO and not the client itself.

Also, next time please create the issue at the page of the specific client. You can find the report a bug button right at the application page inside the app hub.

**Comment by Tartarus6** [comment]
I hadn't seen that I could report bugs in the app. Thanks for the response.
