### ISSUE TITLE
Spanish language

### ISSUE THREAD

**Issue by eddieilish** [ImY0mu/SimpleMMO-Hub-Dist#14]
I just wanted to suggest a Spanish language option for the client. If needed, I could help with it. Thank you!

**Comment by ImY0mu** [comment]
Hello, sure sounds good to me.

I will have to do some final touches to it and then I will share, maybe in a way of a new repository, translation files.

Currently the translation works only at App Hub, Mobile Simulation's menu items and that's it. I will see if I can prepare the others as well.  It will probably take some time tho, as currently I'm very close to deadline of my graduation project and I am working on other projects as well.

**Comment by eddieilish** [comment]
Hey, glad to hear such good news!

I'm also studying for finals, so I'll be busy for the rest of the month. However, I hope we can work this out during the summer holidays! We can keep in touch, don't hesitate to contact me at anytime. :)

Good luck on your project, I wish you the best.

**Comment by ImY0mu** [comment]
Hello again,
I have added folder locales to this repository which contains the currently existing translations. I would suggest to base your translation of the [en.json](https://github.com/ImY0mu/SimpleMMO-Hub-Dist/blob/master/locales/en.json) file.

There is no way to test a new translation by yourself at this moment so you may have to wait for the public release in any of the updates.

Thanks again!

**Comment by eddieilish** [comment]
Hello,
I'll start working on it as soon as I can, thank you again for giving me the opportunity to be part of this project.

I still have to figure out how to submit the final file once I'm done, since I'm not very familiar with GitHub yet, but I doubt it'll be an issue.

Thank you!

**Comment by eddieilish** [comment]
Hey again,

I'm basically done with the translation, though I have a few questions and issues that have come up during the process.

Typos found in the English version:
-"become_a_patreon": "Become a patreon", // should be "Become a patron", since Patreon is the service whilst patrons are the subscribers.
-Settings>General>Show friends>Aavatar only // double "a" on "avatar"

Some questions:
- Does "Hit your marks" refer to anything in-game, or does it just mean "achieve your goals"? Same with "Hug your friends and enemies".
- Should I translate client names, or should I keep the English version? I'm talking about.

I think I'll be able to provide the final locale file once I get to sort those things out.
Thanks!

**Comment by ImY0mu** [comment]
Hey, thanks for the feedback.

Changes then:
• "become_a_patron": "Become a patron" //changed the syntax of the item itself as well
• fixed the typo, noticed it this morning as well :p

Answers to your questions:
• It does mean "achieve your goals". 
• Hug is kinda a slang for murdering players in SMMO. 
• I translated them before so I think it should be fine.

That is great, thanks again.

**Comment by eddieilish** [comment]
Hi, thank you for the information!

I'm done with the translation except for one line I don't quite understand, sorry I didn't include it in the previous request. So, I'm having trouble with “Two-Part generation of targets to avoid rate limit” (Dvoudílné generování cílů, aby se zabránilo omezení hry). I'm not really sure what does it refer to, nor have I been able to figure it out fiddling with the client.

Sorry for the inconvenience.

**Comment by ImY0mu** [comment]
What it does is:
Whenever you generate pvp targets, it does generate only the first half till you get to specific point for it to generate the other half, it does it to prevent the user from getting rate limited in the game.

**Comment by ImY0mu** [comment]
Forgot to mention, I have added two new lines:

"events_notification": "Notifications and Messages notification",
"events_notification_desc": "Notifies you in case you receive a message or a notification"

so would it be possible to include them? Thanks again

**Comment by eddieilish** [comment]
Great! Thank for the explanation :)

I've just added a Pull request with the updated file (with those two new lines)

**Comment by ImY0mu** [comment]
Thank you again!

I will implement the spanish language in the next update, what name should I use to credit you?

**Comment by eddieilish** [comment]
Glad to hear that!

I think **Luis 'Eddie' Sendin** will do it.

On another note, though I'll follow the project closely, don't hesitate to contact me if you need to translate any new lines :)
