### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by EvJack** [ImY0mu/SimpleMMO-Hub-Dist#17]
Hello. I want to make a Russian localization of your project. I wanted to clarify: the file en.json has an up-to-date version? Is it possible to use it as the main file for translation?

**Comment by ImY0mu** [comment]
Greetings, the translation currently is only for App Hub and it is missing some of the latest English texts. I will try update it next Monday and I will let you know here.

**Comment by ImY0mu** [comment]
Greetings, if you are still interestested in making the russian localisation then please do. The file is up to date now. (Web App description is not part of any localisations for now)

**Comment by ImY0mu** [comment]
Closed as the issue has not received any reply in a while.
