### ISSUE TITLE
Add Gold Amount to Home

### ISSUE THREAD

**Issue by WhoIsConch** [ImY0mu/SimpleMMO-Hub-Dist#18]
This hub is great, it shows my health, experience, all of my stats, and some more. But for some reason, my amount of gold isn't here. It seems like that would fit right in.

**Comment by nothing0074** [comment]
it seems like everything in the hub is obtained from the profile but gold in the bank dosent show on the profile so it wouldnt work

**Comment by ImY0mu** [comment]
Greetings, no worries, gold should be easy to add. Only have to think of the right placement.

**Comment by ImY0mu** [comment]
Added in version 0.0.44
