### ISSUE TITLE
step button keeps greying out

### ISSUE THREAD

**Issue by oncmonkey** [ImY0mu/SimpleMMO-Hub-Dist#19]
about once every 2-6 minutes ill get the button greyed out and be forced to refresh 
sofar ive tried reinstalling the app, changing which wifi im on, and Ctrl shift i to find my internal api numbers which never went below 40, and it doesnt happen while im on web.app

after the reinstall it happened on the 2nd step with them 2 steps being the only things i had done in 10 minutes prior in smmo, including phone 

![image_2022-08-29_134235611](https://user-images.githubusercontent.com/9371023/187274570-59819b9e-ac2e-4bc2-a669-8944584ec5c7.png)

**Comment by ImY0mu** [comment]
Greetings, thank you for letting me know. I will try to look into it in my free time. 

Have you changed something in settings of travel screen in SimpleMMO recently or has it just randomly started doing so?

**Comment by oncmonkey** [comment]
it just recently started within last few days, and the only setting i have touched in months is SM or the step position between top and bottom.

 GL with finding the bug and don't rush on my account cause i've found a way to work around it for now

**Comment by ImY0mu** [comment]
I have tried to do something about it, let me know if it fixed the issue you have experienced. 

Thank you.
