### ISSUE TITLE
Missing Recipient Information - Send Item Mobile Sim

### ISSUE THREAD

**Issue by HugTeddy** [ImY0mu/SimpleMMO-Hub-Dist#2]
Hub Version: 0.0.6-21.12.2

The recipient information is missing on the item send page, although the buttons seem to work correctly. 

Web App:
![image](https://user-images.githubusercontent.com/62405530/144271664-d024d4ad-6ecb-4781-8f1f-78bfe63059d2.png)

Mobile Sim:
![image](https://user-images.githubusercontent.com/62405530/144271698-e802e7da-9dfa-47ef-b67f-50608b6c522e.png)

**Comment by ImY0mu** [comment]
Sadly issue on Mike's side, so closing it now.
