### ISSUE TITLE
Disable Discord Rich Presence

### ISSUE THREAD

**Issue by LightBeamOvHe** [ImY0mu/SimpleMMO-Hub-Dist#24]
Hello,

I was wondering if there was a way to disable Discord Rich Presence ? I like to play the game while there's some time on another game (in this case, Overwatch 2) and it doesn't show the game I am playing. I've looked into all options available (I think ?) and even in Discord, but it doesn't appear. Maybe I forgot something ?
Thanks a lot

**Comment by ImY0mu** [comment]
Hello there. I'm sorry about your troubles. I will look into adding an option to disable it. Thank you

**Comment by ImY0mu** [comment]
Added in version 0.0.51

**Comment by LightBeamOvHe** [comment]
Thanks mate, you are an absolute king 👑 Your app is great and became the only way I play the game on PC. Thanks again for your awesome work
