### ISSUE TITLE
Overview tab not working

### ISSUE THREAD

**Issue by 400Bones** [ImY0mu/SimpleMMO-Hub-Dist#26]
Hi,

The overview page which shows when you first open the app hub is showing everything blank except exp. Guild PVP Tool Also not showing anything at all. Mobile sim and chat working fine however though.

![image](https://user-images.githubusercontent.com/119683761/205321359-a4eb0909-55c8-49e1-ad33-85815690f036.png)

![image](https://user-images.githubusercontent.com/119683761/205321448-baafed35-70c0-4a37-bb53-81e5737e5dfd.png)

**Comment by nothing0074** [comment]
im also having the same problems

**Comment by ImY0mu** [comment]
Greetings, I'm sorry to hear about your troubles. Have you tried to sign out and sign back in?

**Comment by ImY0mu** [comment]
Fixed by signing out from all the accounts and then signing back. It occurred because the account was inactive for a while and the game session has ended. One of the users who were experiencing this issue has verified that it helped. Closing the issue now.
