### ISSUE TITLE
Flexible port for mobile client?

### ISSUE THREAD

**Issue by phoenix-295** [ImY0mu/SimpleMMO-Hub-Dist#28]
Can we have a settings on which port the mobile client runs? I have an application which is constantly running on port 8081 and there are other services which communicate with my app on same port

**Comment by ImY0mu** [comment]
Greetings,

I am sorry to hear about your troubles. I spent my lunch break to get it working, I am going to release the update in a bit. You will be able to find the settings under new menu page Network in App Hub's Settings.

![image](https://user-images.githubusercontent.com/49496357/206689069-c7add875-1a6c-44f3-9ae9-0175dce1585f.png)


Version 0.0.55

**Comment by phoenix-295** [comment]
wow thanks!! :)
