### ISSUE TITLE
Opening Deep Links Loads Hub First

### ISSUE THREAD

**Issue by HugTeddy** [ImY0mu/SimpleMMO-Hub-Dist#3]
Opening a deep link such as `smmo://https://web.simple-mmo.com/town` will force the hub to show up first then open it in the mobile sim, rather than directly opening it in the mobile sim. I assume this may be a limitation of the implementation however it would be nice if it popped the mobile sim to the front without having to pop the hub first.

**Comment by ImY0mu** [comment]
Alright, I have changed it so it works as you have mentioned, gonna be in the next update.
