### ISSUE TITLE
"Request for Portuguese Language Option in App

### ISSUE THREAD

**Issue by padoqueira** [ImY0mu/SimpleMMO-Hub-Dist#31]
Hey, I'm Brazilian and I use the app regularly. In my opinion, the app is way superior to the web version or any emulator I've tried. However, I miss an essential feature: the option to use Portuguese, a language with many speakers. It would be very advantageous if the app had this option, as it would facilitate the communication of many people who use the language in their daily lives.

**Comment by ImY0mu** [comment]
Greetings, would you be able to translete it yourself if you were to have access to the translation files?

**Comment by V4mpw0L** [comment]
Hey! I am Brazilian and would be cool to have it translated to pt-br, i can help with the translation.

**Comment by padoqueira** [comment]
> Greetings, would you be able to translete it yourself if you were to have access to the translation files?

I could try, but I’m not a professional in programming. In fact, I don’t know anything. However, it would be a great learning experience to do this.

**Comment by padoqueira** [comment]
> Greetings, would you be able to translete it yourself if you were to have access to the translation files?

I could try, but I’m not a professional in programming. In fact, I don’t know anything. However, it would be a great learning experience to do this.

**Comment by ImY0mu** [comment]
No worries, there is no need to learn any programming. Just copy/download content of the file you wish to translate, rename it to fit the short name of your language and then translate it.

**Files:**
App Hub: https://raw.githubusercontent.com/ImY0mu/SimpleMMO-Hub-Dist/master/locales/en.json
Mobile Simulation: https://raw.githubusercontent.com/ImY0mu/SimpleMMO-Hub-Dist/master/locales_mobile/en.json

**Example:**
```json
"language": "Language",
```
to
```json
"language": "The world your language uses for language",
```

**Comment by padoqueira** [comment]
Hello again. Sorry for the delay, but here are the two files translated into Portuguese: https://www.mediafire.com/file/ez9gkk3nfa1nm37/simplemmo_portuguese_translation.zip/file

**Comment by ImY0mu** [comment]
Thank you, I will add it today.
