### ISSUE TITLE
Can you please implement being able to see other party members stepping, like in the app and web app?

### ISSUE THREAD

**Issue by MazokuFR** [ImY0mu/SimpleMMO-Hub-Dist#36]
Currently when you are in a stepping party you have no indication on if your party members are active or not without going through the party menus which isn't as convenient as seeing them actively stepping.

**Comment by MazokuFR** [comment]
MoE just informed me it can be fixed by minimizing and re-opening. Thank you for your work

**Comment by ImY0mu** [comment]
Greetings and apologies for the troubles,

When I looked into the issue back in 21/04/2022, it was not something I could fix on my side.

I am currently working on updating the dependency (Electron framework) that handles the loading of website content, so hopefully it will fix itself with the newer version of Chromium,.

The current working fix is:
Minimize the window and then re-focus it again.
