### ISSUE TITLE
Mobile Sim Launch Issue

### ISSUE THREAD

**Issue by HugTeddy** [ImY0mu/SimpleMMO-Hub-Dist#4]
Issue launching mobile sim, launcher works the first time opens correctly, however, subsequent launches cause errors. 
1. Looks like the popups are related to launching the mobile sim, the more times you try to open it, the more error messages
2. This issue resolves on computer restart till you close the mobile sim again
3. Mobile sim does not close with "X" button on top right

![image](https://user-images.githubusercontent.com/62405530/144694379-45e2fe8f-e6a9-4c01-b12f-4bb800d84882.png)

Sim Version: 0.0.12
Hub Version: 2021/12/4 v0.0.8

**Comment by ImY0mu** [comment]
From what I can tell, It happened due to poor handling of what to do when the patreon end point is down, will be fixed in next update.
