### ISSUE TITLE
Friend Bar Styles

### ISSUE THREAD

**Issue by HugTeddy** [ImY0mu/SimpleMMO-Hub-Dist#5]
Allow users to choose a style for friend bars like Discords compact or expanded. Allowing users to choose a sleeker design with only name and status. Like Gmail chat/contact lists.
![image](https://user-images.githubusercontent.com/62405530/144694582-a2737417-f25a-41fd-a856-f746a8898869.png)

**Comment by ImY0mu** [comment]
Do you mean hide the avatar and show just the name and status?

**Comment by HugTeddy** [comment]
Yeah possibly as an alternative style

**Comment by ImY0mu** [comment]
It has been added in the new update.
