### ISSUE TITLE
Hub Sizing Options

### ISSUE THREAD

**Issue by HugTeddy** [ImY0mu/SimpleMMO-Hub-Dist#9]
Consider offering two/three different window sizes or people with large/small screens and those visually impared

**Comment by ImY0mu** [comment]
![image](https://user-images.githubusercontent.com/49496357/145705470-94064489-09f9-4915-b5da-8d791d924c04.png)

Would this be enough?

**Comment by HugTeddy** [comment]
Yeah I feel like that should be plenty

**Comment by ImY0mu** [comment]
Alright, will be added in the next update.
